[package]
name = "zmq_Server"
version = "0.1.0"
edition = "2021"

[dependencies]
zmq = "0.9"
rand = "0.7.0"
time = "0.1.41"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }